sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nekaartajaya/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -it -e CI=true nekaartajaya/react-test npm run test

after-succes:
  - docker build -t nekaartajaya/multi-client ./client
  - docker build -t nekaartajaya/multi-nginx ./nginx
  - docker build -t nekaartajaya/multi-server ./server
  - docker build -t nekaartajaya/multi-worker ./worker
  # Login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub
  - docker push nekaartajaya/multi-client 
  - docker push nekaartajaya/multi-nginx 
  - docker push nekaartajaya/multi-server 
  - docker push nekaartajaya/multi-worker