language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t nekaartajaya/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true nekaartajaya/react-test npm test -- --watchAll=false

after_success:
 - docker build -t nekaartajaya/multi-client ./client
 - docker build -t nekaartajaya/multi-nginx ./nginx
 - docker build -t nekaartajaya/multi-server ./server
 - docker build -t nekaartajaya/multi-worker ./worker
#  Login to docker hub
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#  take image to docker hub
 - docker push nekaartajaya/multi-client
 - docker push nekaartajaya/multi-nginx
 - docker push nekaartajaya/multi-server
 - docker push nekaartajaya/multi-worker